/*
 [df:title]
 荷札ヤマトデータを取得します。

 [df:description]
  SQL Description here.

*/

-- #df:entity#

-- !df:pmb extends Paging!
-- !!AutoDetect!!
SELECT
   MAX(MCZ.ARRIVAL_STORE_CD) AS ARRIVAL_STORE_CD,
   MAX(TSIH.DELIV_TEL_NO) AS DELIV_TEL_NO,
   MAX(TSIH.DELIV_ZIP_CD) AS DELIV_ZIP_CD,
   CONCAT(IFNULL(MAX(TSIH.DELIV_ADDRESS1),''),IFNULL(MAX(TSIH.DELIV_ADDRESS2),'')) AS DELIV_ADDRESS,
   CONCAT(IFNULL(MAX(TSIH.DELIV_CUSTOMER_NM1),''),IFNULL(MAX(TSIH.DELIV_CUSTOMER_NM2),'')) AS DELIV_CUSTOMER_NM,
   MAX(MCSY.SLIP_CLIENT_TEL_NO) AS SLIP_CLIENT_TEL_NO,
   MAX(MCSY.SLIP_CLIENT_ZIP_CD) AS SLIP_CLIENT_ZIP_CD,
   CONCAT(IFNULL(MAX(MCSY.SLIP_CLIENT_ADDRESS1),''),IFNULL(MAX(MCSY.SLIP_CLIENT_ADDRESS2),''),IFNULL(MAX(MCSY.SLIP_CLIENT_ADDRESS3),''),IFNULL(MAX(MCSY.SLIP_CLIENT_ADDRESS4),'')) AS SLIP_CLIENT_ADDRESS,
   MAX(MCSY.SLIP_CLIENT_NM) AS SLIP_CLIENT_NM,
   MAX(TPAH.CARRIER_TRACE_NUM) AS CARRIER_TRACE_NUM,
   MAX(TAIH.WORK_DT) AS WORK_DT,
   MAX(TAIH.DELIV_DT) AS DELIV_DT,
   MAX(TAIH.DELIV_TZ) AS DELIV_TZ,
   CONCAT(IFNULL(MAX(MCSY.SLIP_ITEM_CD1),''),IFNULL(MAX(MCSY.SLIP_ITEM_NM1),''),IFNULL(MAX(MCSY.SLIP_ITEM_CD2),''),IFNULL(MAX(MCSY.SLIP_ITEM_NM2),'')) AS SLIP_ITEM_NM,
   MAX(TPAH.SHIPPING_PACKING_NO) AS BOX_NO,
   MAX(TPAH1.SHIPPING_PACKING_NO) AS BOX_NO_SUM,
   MAX(MCSY.ARTICLE) AS ARTICLE,
   MAX(MCB.BOX_SIZE_CD) AS BOX_SIZE_CD,
   MAX(MCSY.SEND_CD) AS SEND_CD,
   MAX(TPIH.NIZOROE_NO) AS NIZOROE_NO,
   MAX(TPAH.CARRIER_TRACE_NUM) AS TRACKING_NO,
   MAX(TSIH.DELIV_TEL_NO) AS DELIV_TEL_NO_H,
   MAX(TSIH.DELIV_ZIP_CD) AS DELIV_ZIP_CD_H,
   CONCAT(IFNULL(MAX(TSIH.DELIV_ADDRESS1),''),IFNULL(MAX(TSIH.DELIV_ADDRESS2),'')) AS DELIV_ADDRESS_H,
   CONCAT(IFNULL(MAX(TSIH.DELIV_CUSTOMER_NM1),''),IFNULL(MAX(TSIH.DELIV_CUSTOMER_NM2),'')) AS DELIV_CUSTOMER_NM_H,
   MAX(MCSY.SLIP_CLIENT_TEL_NO) AS SLIP_CLIENT_TEL_NO_H,
   MAX(MCSY.SLIP_CLIENT_ZIP_CD) AS SLIP_CLIENT_ZIP_CD_H,
   CONCAT(IFNULL(MAX(MCSY.SLIP_CLIENT_ADDRESS1),''),IFNULL(MAX(MCSY.SLIP_CLIENT_ADDRESS2),''),IFNULL(MAX(MCSY.SLIP_CLIENT_ADDRESS3),''),IFNULL(MAX(MCSY.SLIP_CLIENT_ADDRESS4),'')) AS SLIP_CLIENT_ADDRESS_H,
   MAX(MCSY.SLIP_CLIENT_NM) AS SLIP_CLIENT_NM_H,
   MAX(TPAH.CARRIER_TRACE_NUM) AS CARRIER_TRACE_NUM_H,
   MAX(TAIH.WORK_DT) AS WORK_DT_H,
   MAX(TAIH.DELIV_DT) AS DELIV_DT_H,
   MAX(TAIH.DELIV_TZ) AS DELIV_TZ_H,
   CONCAT(IFNULL(MAX(MCSY.SLIP_ITEM_CD1),''),IFNULL(MAX(MCSY.SLIP_ITEM_NM1),''),IFNULL(MAX(MCSY.SLIP_ITEM_CD2),''),IFNULL(MAX(MCSY.SLIP_ITEM_NM2),'')) AS SLIP_ITEM_NM_H,
   MAX(MCSY.ARTICLE) AS ARTICLE_H,
   MAX(MCSY.SEND_CD) AS SEND_CD_H,
   MAX(TPAH.CARRIER_TRACE_NUM) AS TRACKING_NO_H,
   MAX(TPAH.SHIPPING_PACKING_NO) AS BOX_NO_H,
   MAX(TPAH1.SHIPPING_PACKING_NO) AS BOX_NO_H_SUM,
   MDC.DELIVERY_COURSE_NM
FROM
    T_ALLOC_INST_H TAIH
    INNER JOIN T_SHIPPING_INST_H TSIH
        ON TAIH.ALLOC_INST_H_ID = TSIH.ALLOC_INST_H_ID
        AND TSIH.DEL_FLG = '0'
    INNER JOIN T_SHIPPING_INST_B TSIB
        ON TSIH.SHIPPING_INST_H_ID = TSIB.SHIPPING_INST_H_ID
        AND TSIB.DEL_FLG = '0'
    INNER JOIN T_PICKING_H TPIH
        ON TPIH.ALLOC_INST_H_ID = TAIH.ALLOC_INST_H_ID
        AND TPIH.DEL_FLG = '0'
    INNER JOIN T_PICKING_R TPIR
        ON TPIR.PICKING_H_ID = TPIH.PICKING_H_ID
        AND TPIR.DEL_FLG = '0'
    LEFT JOIN M_CENTER MCE
        ON MCE.CENTER_ID = TAIH.CENTER_ID
        AND MCE.DEL_FLG = '0'
    LEFT JOIN T_PACKING_H TPAH
        ON TPAH.PICKING_H_ID = TPIH.PICKING_H_ID
        AND TPAH.DEL_FLG = '0'
    LEFT JOIN M_DELIVERY_COURSE MDC
        ON MDC.DELIVERY_COURSE_ID = TSIH.DELIVERY_COURSE_ID
        AND MDC.DEL_FLG = '0'
    LEFT JOIN M_CARRIER_SLIP_YMT MCSY
        ON MCSY.CARRIER_SLIP_YMT_ID = MDC.CARRIER_SLIP_YMT_ID
        AND MCSY.DEL_FLG = '0'
    LEFT JOIN M_CARRIER MC
        ON MC.CARRIER_ID = TSIH.CARRIER_ID
        AND MC.DEL_FLG = '0'
    LEFT JOIN M_COMMON_CARRIER MCC
        ON MCC.COMMON_CARRIER_ID = MC.COMMON_CARRIER_ID
        AND MCC.DEL_FLG = '0'
    LEFT JOIN M_CARRIER_BOX MCB
        ON MCB.CARRIER_ID = MC.CARRIER_ID
        AND MCB.DEL_FLG = '0'
    LEFT JOIN M_CARRIER_ZIP MCZ
        ON MCZ.COMMON_CARRIER_ID = MCC.COMMON_CARRIER_ID
        AND MCZ.DEL_FLG = '0'
    LEFT JOIN M_CUSTOMER MCU
        ON MCU.CUSTOMER_ID = TSIH.DELIV_CUSTOMER_ID
        AND MCU.DEL_FLG = '0'
    LEFT JOIN M_SALES_ORG MSO
        ON MSO.SALES_ORG_ID = MCU.SALES_ORG_ID
        AND MSO.DEL_FLG = '0'
    LEFT JOIN (
        SELECT
            MAX(SHIPPING_PACKING_NO) AS SHIPPING_PACKING_NO
            , NIZOROE_NO
        FROM
            T_PACKING_H
        WHERE
            DEL_FLG = '0'
        GROUP BY
            NIZOROE_NO
    ) TPAH1
        ON TPAH1.NIZOROE_NO = TPAH.NIZOROE_NO
  WHERE TAIH.DEL_FLG = '0'
    /*IF pmb.controlNo != null*/
    AND TPIR.CONTROL_NO = /*pmb.controlNo*/11111111111
    /*END*/
    /*IF pmb.nizoroeNo2 != null*/
    AND TSIH.NIZOROE_NO2 = /*pmb.nizoroeNo2*/'000001'
    /*END*/
 GROUP BY
    MCE.CENTER_CD
    , TSIH.SHIPPING_DT
    , TPIH.DAIHYO_NIZOROE_NO
    , TPIH.NIZOROE_NO
    , TPAH.SHIPPING_PACKING_NO
ORDER BY
    MCE.CENTER_CD
    , TSIH.SHIPPING_DT
    , TPIH.DAIHYO_NIZOROE_NO
    , TPIH.NIZOROE_NO
    , TPAH.SHIPPING_PACKING_NO
