/*
 [df:title]
棚卸関連リスト発行 商品別棚卸実績表兼差異表

 [df:description]
  SQL Description here.
*/
-- #df:entity#
-- !df:pmb!
-- !!AutoDetect!!
SELECT
       SUM(BODY.CHARGE_NUM) AS CHARGE_NUM,
       SUM(BODY.INVENTORY_NUM) AS INVENTORY_NUM,
       (CASE WHEN (
           SELECT CS.CUSTOMER_CD
           FROM M_CUSTOMER CS
           WHERE CS.CUSTOMER_ID = BODY.DEPOSIT_ID
           AND CS.DEL_FLG = '0'
           )  IN ('P135', 'P161', 'P801', 'P900')
           THEN ''
           ELSE (CASE WHEN (CASE WHEN
               BODY.ACCOUNT_ID IS NULL
               THEN NULL
               ELSE (SELECT (CASE WHEN CUSTOMER_NM IS NULL THEN CS2.CUSTOMER_CD ELSE CONCAT_WS(':',CS2.CUSTOMER_CD,CS2.CUSTOMER_NM) END) -- ユーザーCD:ユーザー名
               FROM M_CUSTOMER CS2
               WHERE CS2.CUSTOMER_ID = BODY.ACCOUNT_ID
                   AND CS2.DEL_FLG = '0')
                   END) IS NULL
               THEN (SELECT ( CASE WHEN CONCAT(MSALES.TENHANSHA_NM1, MSALES.TENHANSHA_NM2) IS NULL THEN MSALES.SALES_ORG_CD ELSE CONCAT_WS(':',MSALES.SALES_ORG_CD,CONCAT(MSALES.TENHANSHA_NM1, MSALES.TENHANSHA_NM2)) END) -- 販売組織CD：販売組織名称
                      FROM M_SALES_ORG MSALES WHERE MSALES.SALES_ORG_ID = BODY.SALES_ORG_ID
                       AND MSALES.DEL_FLG = '0')
               ELSE  (CASE WHEN (SELECT ( CASE WHEN CONCAT(MSALES.TENHANSHA_NM1, MSALES.TENHANSHA_NM2) IS NULL THEN MSALES.SALES_ORG_CD ELSE CONCAT_WS(':',MSALES.SALES_ORG_CD,CONCAT(MSALES.TENHANSHA_NM1, MSALES.TENHANSHA_NM2)) END) -- 販売組織CD：販売組織名称
                      FROM M_SALES_ORG MSALES WHERE MSALES.SALES_ORG_ID = BODY.SALES_ORG_ID
                       AND MSALES.DEL_FLG = '0') IS NULL THEN NULL
                   ELSE
                       CONCAT_WS('/',(SELECT ( CASE WHEN CONCAT(MSALES.TENHANSHA_NM1, MSALES.TENHANSHA_NM2) IS NULL THEN MSALES.SALES_ORG_CD ELSE CONCAT_WS(':',MSALES.SALES_ORG_CD,CONCAT(MSALES.TENHANSHA_NM1, MSALES.TENHANSHA_NM2)) END) -- 販売組織CD：販売組織名称
                      FROM M_SALES_ORG MSALES WHERE MSALES.SALES_ORG_ID = BODY.SALES_ORG_ID
                       AND MSALES.DEL_FLG = '0'),(SELECT (CASE WHEN CUSTOMER_NM IS NULL THEN CS2.CUSTOMER_CD ELSE CONCAT_WS(':',CS2.CUSTOMER_CD,CS2.CUSTOMER_NM) END) -- ユーザーCD:ユーザー名
               FROM M_CUSTOMER CS2
               WHERE CS2.CUSTOMER_ID = BODY.ACCOUNT_ID
                   AND CS2.DEL_FLG = '0'))
                       END)
                   END)
        END) AS SALESNAME,
       (CASE WHEN HEAD.PLANT_CD IS NOT NULL  AND HEAD.STORAGE_SPACE_CD IS NOT NULL
           THEN PLANT.PLANT_NM
           ELSE ''
        END) AS PLANTNM,
       HEAD.PLANT_CD AS PLANT_CD,
       HEAD.INVENTORY_DT AS INVENTORY_DT,
       CENTER.CENTER_CD AS CENTER_CD,
       CENTER.CENTER_ABBR AS CENTER_ABBR,
       PRODUCT.PRODUCT_CD AS PRODUCT_CD,
       PRODUCT.PRODUCT_NM AS PRODUCT_NM,
       PRODUCT.JAN_CD AS JAN_CD,
       PRODUCT.PRODUCT_CATEGORY_CLS AS PRODUCT_CATEGORY_CLS,
       PRODUCT.EVALUATION_UNIT_PRICE AS EVALUATION_UNIT_PRICE
  FROM T_INVENTORY_B BODY
    INNER JOIN T_INVENTORY_H HEAD
      ON BODY.INVENTORY_H_ID = HEAD.INVENTORY_H_ID
     AND HEAD.DEL_FLG = '0'
    INNER JOIN M_CENTER CENTER
      ON HEAD.CENTER_ID = CENTER.CENTER_ID
     AND CENTER.DEL_FLG = '0'
    LEFT OUTER JOIN M_SALES_ORG SALESORG
      ON BODY.SALES_ORG_ID = SALESORG.SALES_ORG_ID
     AND SALESORG.DEL_FLG = '0'
    LEFT OUTER JOIN M_PLANT_STORAGE_SPACE PLANT
      ON HEAD.PLANT_CD = PLANT.PLANT_CD
     AND HEAD.STORAGE_SPACE_CD = PLANT.STORAGE_SPACE_CD
     AND PLANT.DEL_FLG = '0'
    LEFT OUTER JOIN M_CUSTOMER CUSTOMER
      ON BODY.DEPOSIT_ID = CUSTOMER.CUSTOMER_ID
     AND CUSTOMER.DEL_FLG = '0'
    LEFT OUTER JOIN M_PRODUCT PRODUCT
      ON BODY.PRODUCT_ID = PRODUCT.PRODUCT_ID
     AND PRODUCT.DEL_FLG = '0'
    LEFT OUTER JOIN M_WAREHOUSE WAREHOUSE
      ON BODY.WAREHOUSE_ID = WAREHOUSE.WAREHOUSE_ID
     AND WAREHOUSE.DEL_FLG = '0'
 WHERE CENTER.CENTER_CD = /*pmb.centerCd*/'C001'
   /*IF pmb.depCustomerCd != null*/
    AND CUSTOMER.CUSTOMER_CD = /*pmb.depCustomerCd*/'P135'
  /*END*/
 /*IF pmb.inventoryDt != null*/
   AND HEAD.INVENTORY_DT = /*pmb.inventoryDt*/'20170412'
 /*END*/
     /*IF pmb.isInventoryDiff*/          -- 検索.棚卸差異が「 01：差異ありのみ出力」の場合、以下を設定
   AND BODY.CHARGE_NUM <> BODY.INVENTORY_NUM
     /*END*/
   AND BODY.DEL_FLG = '0'
GROUP BY SALESNAME,
         PLANT_CD,
         PLANTNM,
         INVENTORY_DT,
         CENTER_CD,
         CENTER_ABBR,
         CENTER_CD,
         CENTER_ABBR,
         PRODUCT_CD,
         PRODUCT_NM,
         JAN_CD,
         PRODUCT_CATEGORY_CLS,
         EVALUATION_UNIT_PRICE
 ORDER BY CENTER.CENTER_CD ASC,
 WAREHOUSE.WAREHOUSE_CD ASC,
 HEAD.PLANT_CD ASC,
 HEAD.INVENTORY_DT ASC,
  SALESNAME ASC,
  PRODUCT.PRODUCT_CATEGORY_CLS ASC,
  PRODUCT.PRODUCT_CD ASC,
  PRODUCT.JAN_CD ASC